import { useEffect, useMemo, useState } from "react";

const tabs = [["dashboard", "⌂", "Dashboard"], ["donations", "＋", "Donations"], ["pickups", "⌚", "Pickup coordination"], ["inventory", "▣", "Inventory"], ["recipients", "⌘", "Recipients"], ["volunteers", "♧", "Volunteers"], ["reports", "▤", "Reports"]];
let authToken = localStorage.getItem("shareplate_token") || "";
const api = async (url, options = {}) => { const r = await fetch(url, { ...options, headers: { ...(options.headers || {}), ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}) } }); if (!r.ok) throw new Error((await r.json().catch(() => ({}))).error || "Request failed."); return r.status === 204 ? null : r.json(); };
const badge = (value) => <span className={`badge ${value === "Urgent" ? "urgent" : value === "Scheduled" ? "scheduled" : ""}`}>{value}</span>;
const status = (item) => item.pickup ? "Scheduled" : item.priority;
const action = (label, onClick, type = "button") => <button className="btn small" type={type} onClick={onClick}>{label}</button>;

export default function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem("shareplate_user") || "null"));
  const [active, setActive] = useState("dashboard");
  const [data, setData] = useState(null);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const load = async () => { try { setData(await api("/api/data")); } catch (e) { setError(e.message); } };
  useEffect(() => { if (user) load(); }, [user]);
  const message = (text, bad = false) => { (bad ? setError : setNotice)(text); setTimeout(() => (bad ? setError : setNotice)(""), 3500); };
  const post = async (endpoint, body, success) => { try { await api(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); await load(); message(success); } catch (e) { message(e.message, true); } };
  const patch = async (id, body, success) => { try { await api(`/api/donations/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); await load(); message(success); } catch (e) { message(e.message, true); } };
  const remove = async (resource, id) => { try { await api(`/api/${resource}/${id}`, { method: "DELETE" }); await load(); message("Record removed."); } catch (e) { message(e.message, true); } };
  const metrics = useMemo(() => { const d = data?.donations || []; const meals = d.reduce((n, item) => n + Number(item.meals), 0); return { meals, kg: Math.round(meals * .45), pickups: d.filter((x) => x.pickup).length, donors: new Set(d.map((x) => x.donor)).size }; }, [data]);
  const signOut = () => { localStorage.removeItem("shareplate_token"); localStorage.removeItem("shareplate_user"); authToken = ""; setData(null); setUser(null); };
  if (!user) return <Auth onAuth={(result) => { authToken = result.token; localStorage.setItem("shareplate_token", result.token); localStorage.setItem("shareplate_user", JSON.stringify(result.user)); setUser(result.user); }}/>;
  if (!data) return <main className="loading">{error || "Loading SharePlate…"}</main>;
  const visibleTabs = tabs.filter(([id]) => user.role === "admin" || user.role === "ngo" || id === "dashboard" || (user.role === "donor" && id === "donations") || (user.role === "recipient" && id === "recipients") || (user.role === "volunteer" && id === "volunteers"));
  return <div className="app"><aside><div className="brand"><b>♥</b>SharePlate</div><nav>{visibleTabs.map(([id, icon, label]) => <button key={id} className={active === id ? "active" : ""} onClick={() => setActive(id)}>{icon} &nbsp;{label}</button>)}</nav><p className="side-note">Food should nourish people, not landfills.</p></aside>
    <main><div className="top"><span>Operations / <strong>{active[0].toUpperCase() + active.slice(1)}</strong></span><span className="user">{user.name} · {user.role} <button className="link-btn" onClick={signOut}>Sign out</button></span></div>{notice && <div className="notice">{notice}</div>}{error && <div className="notice error">{error}</div>}
      {active === "dashboard" && <Dashboard data={data} metrics={metrics} go={setActive}/>}
      {active === "donations" && <Donations create={(v) => post("/api/donations", v, "Donation published. Inventory, pickup board and reports are updated.")} remove={(id) => remove("donations", id)} donations={data.donations}/>}
      {active === "pickups" && <Pickups donations={data.donations} recipients={data.recipients} patch={patch}/>}
      {active === "inventory" && <Inventory donations={data.donations} recipients={data.recipients}/>}
      {active === "recipients" && <Recipients items={data.recipients} create={(v) => post("/api/recipients", v, "Recipient organisation added.")} remove={(id) => remove("recipients", id)}/>}
      {active === "volunteers" && <Volunteers items={data.volunteers} create={(v) => post("/api/volunteers", v, "Volunteer added.")} remove={(id) => remove("volunteers", id)}/>}
      {active === "reports" && <Reports metrics={metrics} donations={data.donations} recipients={data.recipients}/>}
    </main></div>;
}
function Auth({ onAuth }) { const [register, setRegister] = useState(false); const [error, setError] = useState(""); const submit = async (e) => { e.preventDefault(); const values = Object.fromEntries(new FormData(e.currentTarget)); try { onAuth(await api(register ? "/api/auth/register" : "/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) })); } catch (err) { setError(err.message); } }; return <div className="auth"><section className="auth-card"><div className="brand auth-brand"><b>♥</b>SharePlate</div><h1>{register ? "Create your account" : "Welcome back"}</h1><p>Manage food rescue safely with your role-based workspace.</p>{error && <div className="notice error">{error}</div>}<form onSubmit={submit}>{register && <><label className="field">Your name<input required name="name" placeholder="Full name"/></label><label className="field">Role<select name="role"><option value="donor">Food donor</option><option value="ngo">NGO coordinator</option><option value="recipient">Recipient organisation</option><option value="volunteer">Volunteer</option></select></label><label className="field">Organisation (optional)<input name="organisation" placeholder="Organisation name"/></label></>}<label className="field">Email<input required name="email" type="email" placeholder="you@example.com"/></label><label className="field">Password<input required name="password" type="password" minLength="8" placeholder="At least 8 characters"/></label><button className="btn full">{register ? "Create account" : "Sign in"}</button></form><button className="switch" onClick={() => { setRegister(!register); setError(""); }}>{register ? "Already registered? Sign in" : "New here? Create an account"}</button></section></div>; }
function Dashboard({ data, metrics, go }) { const percent = Math.min(100, Math.round(metrics.kg / 180 * 100)); return <><Header title="Good morning, Green Hands" text="Here is today’s food rescue activity." button="+ Add donation" click={() => go("donations")}/><div className="grid stats"><Stat label="Available donations" value={data.donations.filter((x) => !x.pickup).length} hint="Ready to collect"/><Stat label="Meals rescued" value={metrics.meals} hint="This month"/><Stat label="Pickups today" value={metrics.pickups} hint="Scheduled routes"/><Stat label="Active volunteers" value={data.volunteers.length} hint="Ready to help"/></div><div className="grid cols"><section className="card"><h2>Latest food donations</h2>{data.donations.slice(-4).reverse().map((d) => <div className="item" key={d._id}><div className="ico">🍱</div><div className="grow"><div className="name">{d.food}</div><div className="detail">{d.donorName} · {d.meals} meals · {d.area}</div></div>{badge(status(d))}</div>)}</section><div className="grid"><section className="card impact"><h2>Community impact</h2><div className="value">{metrics.kg} kg</div><p className="detail">Surplus food kept in the community, not sent to landfill.</p><div className="bar"><i style={{ width: `${percent}%` }}/></div><span className="detail">{percent}% of monthly goal</span></section><section className="card"><h2>Today’s action list</h2>{data.donations.filter((d) => !d.pickup).map((d) => <div className="item" key={d._id}><div className="ico">↗</div><div className="grow"><div className="name">Collect from {d.donorName}</div><div className="detail">Before {d.expiry} · {d.area}</div></div></div>)}</section></div></div></>; }
function Donations({ create, donations, remove }) { return <><Header title="Food donations" text="Record surplus food and make it visible for collection."/><Form title="New donation" fields={[["Food type", "food", "text", "Cooked meals"], ["Estimated meals", "meals", "number", "80"], ["Best before", "expiry", "time"], ["Pickup area", "area", "text", "Central Market"], ["Priority", "priority", "select", ["Available", "Urgent"]]]} submit={create} button="Publish donation"/><section className="card table"><h2>Donation register</h2><table><thead><tr><th>Food</th><th>Donor</th><th>Meals</th><th>Status</th><th></th></tr></thead><tbody>{donations.slice().reverse().map((d) => <tr key={d._id}><td><strong>{d.food}</strong></td><td>{d.donorName}</td><td>{d.meals}</td><td>{badge(status(d))}</td><td>{action("Remove", () => remove(d._id))}</td></tr>)}</tbody></table></section></>; }
function Pickups({ donations, recipients, patch }) { return <><Header title="Pickup coordination" text="Schedule collection and match food to recipient organisations."/><section className="card table"><table><thead><tr><th>Donation</th><th>Location</th><th>Expiry</th><th>Recipient</th><th>Collection</th></tr></thead><tbody>{donations.map((d) => <tr key={d._id}><td><strong>{d.food}</strong><br/><small>{d.donorName} · {d.meals} meals</small></td><td>{d.area}</td><td>{d.expiry}</td><td><select value={d.recipient || ""} onChange={(e) => patch(d._id, { recipient: e.target.value || null }, "Recipient assignment saved.")}><option value="">Assign recipient</option>{recipients.map((r) => <option value={r.user} key={r._id}>{r.name}</option>)}</select></td><td>{d.pickup ? badge("Scheduled") : action("Schedule pickup", () => patch(d._id, { pickup: true }, "Pickup scheduled."))}</td></tr>)}</tbody></table></section></>; }
function Inventory({ donations, recipients }) { const recipient = (id) => recipients.find((x) => String(x.user) === String(id))?.name || "Unassigned"; return <><Header title="Food inventory" text="First-expiring-first-out view of available food."/><section className="card table"><table><thead><tr><th>Food donation</th><th>Meals</th><th>Area</th><th>Best before</th><th>Recipient</th><th>Status</th></tr></thead><tbody>{donations.slice().sort((a,b) => a.expiry.localeCompare(b.expiry)).map((d) => <tr key={d._id}><td><strong>{d.food}</strong><br/><small>{d.donorName}</small></td><td>{d.meals}</td><td>{d.area}</td><td>{d.expiry}</td><td>{recipient(d.recipient)}</td><td>{badge(status(d))}</td></tr>)}</tbody></table></section></>; }
function Recipients({ items, create, remove }) { return <><Header title="Recipient network" text="Register organisations and their food requirements."/><Form title="Add recipient organisation" fields={[["Organisation", "name", "text", "Neighbourhood Shelter"], ["Meals needed", "meals", "number", "50"], ["Area", "area", "text", "Central Market"], ["Dietary notes", "notes", "text", "Vegetarian preferred"], ["Contact", "contact", "email", "contact@example.org"]]} submit={create} button="Add recipient"/><List title="Registered recipients" heads={["Organisation", "Meals needed", "Dietary notes", "Area", "Contact", ""]} rows={items.map((x) => [<strong>{x.name}</strong>, x.meals, x.notes, x.area, x.contact, action("Remove", () => remove(x.id))])}/></>; }
function Volunteers({ items, create, remove }) { return <><Header title="Volunteer management" text="Register volunteers, skills and availability."/><Form title="Add volunteer" fields={[["Name", "name", "text", "Aarav Sharma"], ["Role / skill", "role", "text", "Pickup driver"], ["Availability", "availability", "text", "Weekends, 10 AM-4 PM"], ["Hours contributed", "hours", "number", "0"], ["Phone", "phone", "tel", "98765 43210"]]} submit={create} button="Add volunteer"/><List title="Volunteer directory" heads={["Volunteer", "Role", "Availability", "Hours", "Phone", ""]} rows={items.map((x) => [<strong>{x.name}</strong>, x.role, x.availability, `${x.hours} hrs`, x.phone, action("Remove", () => remove(x.id))])}/></>; }
function Reports({ metrics, donations, recipients }) { const assigned = donations.filter((d) => d.recipientId).length; return <><Header title="Impact reports" text="Live operational and community impact summary."/><div className="grid stats"><Stat label="Meals available" value={metrics.meals} hint="Across all donations"/><Stat label="Food diverted" value={`${metrics.kg} kg`} hint="Estimated impact"/><Stat label="Donor partners" value={metrics.donors} hint="Active partners"/><Stat label="Scheduled pickups" value={metrics.pickups} hint="Collection routes"/></div><section className="card report"><h2>Distribution readiness</h2><p className="detail"><strong>{assigned}</strong> of {donations.length} donations have a recipient assignment. {recipients.length} recipient organisations are registered in the network.</p><div className="bar"><i style={{ width: `${donations.length ? Math.round(assigned / donations.length * 100) : 0}%` }}/></div></section></>; }
function Header({ title, text, button, click }) { return <header className="head"><div><h1>{title}</h1><p>{text}</p></div>{button && <button className="btn" onClick={click}>{button}</button>}</header>; }
function Stat({ label, value, hint }) { return <section className="card"><div className="label">{label}</div><div className="value">{value}</div><div className="green">{hint}</div></section>; }
function Form({ title, fields, submit, button }) { const send = (e) => { e.preventDefault(); submit(Object.fromEntries(new FormData(e.currentTarget))); e.currentTarget.reset(); }; return <form className="card form" onSubmit={send}><h2>{title}</h2><div className="formgrid">{fields.map(([label, name, type, arg]) => <label className="field" key={name}>{label}{type === "select" ? <select name={name}>{arg.map((v) => <option key={v}>{v}</option>)}</select> : <input required={["name","donor","food","meals","time","area","role","availability"].includes(name)} name={name} type={type} min={type === "number" ? "0" : undefined} placeholder={arg}/>}</label>)}</div><button className="btn">{button}</button></form>; }
function List({ title, heads, rows }) { return <section className="card table"><h2>{title}</h2><table><thead><tr>{heads.map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table></section>; }
